apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: gateway 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway 
    spec:
      containers:
        - name: gateway 
          image: admin9.azurecr.io/gateway
          ports:
          - containerPort: 8080